window.HSE = window.HSE || {};
HSE.config = {
  appName: 'HSE Performance Management',
  version: 'Enterprise 1.0.0',
  pages: [
    ['executive', 'Executive Summary', 'layout-dashboard'],
    ['safety', 'Safety', 'shield-alert'],
    ['audit', 'Audit & Inspection', 'clipboard-check'],
    ['capa', 'CAPA Center', 'clipboard-list'],
    ['environment', 'Environment', 'leaf'],
    ['project', 'Project Improvement', 'rocket'],
    ['permit', 'Permit To Work', 'file-check-2'],
    ['analytics', 'Analytics & Trends', 'chart-no-axes-combined'],
    ['reports', 'Reports', 'file-text'],
    ['settings', 'Settings', 'settings'],
  ],
  months: ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'],
  departments: ['General Affair', 'Engineering', 'PPIC', 'Quality Control', 'Distribusi', 'Produksi'],
  areas: ['R. Kerja Engineer', 'Workshop', 'R. Panel', 'R. Genset', 'R. Kompresor', 'Water Treatment', 'Groundtank', 'Lab QC', 'Repacking Sampel', 'Office Lantai 1', 'Office Lantai 2', 'Candra Kirana', 'Gatot Kaca', 'Mushola As-Sanima', 'Mushola Lobby', 'Toilet Lobby Bawah', 'Toilet Produksi', 'Kantin', 'Taman Outdoor', 'Loker', 'R. Terusan Reservoir', 'Limbah B3', 'Limbah Non B3', 'Parkiran', 'Lorong Samping Gudang', 'R. Kesehatan', 'R. Antara Multi', 'R. Blow', 'R. Packing Botol', 'R. Filling Cup', 'R. Packing Cup', 'R. Rinsing Galon', 'R. Filling Galon', 'Transporter & Feeder Botol', 'Loading RM', 'Gudang RM', 'Gudang FG', 'Loading FG', 'R. Spv Admin'],
  risks: ['Low', 'Medium', 'High', 'Critical'],
  statuses: ['Open', 'On Progress', 'Closed', 'Overdue', 'Expired', 'Active', 'Delayed', 'Cancelled'],
  priorities: ['Low', 'Medium', 'High', 'Critical'],
  permitTypes: ['Confined Space', 'Hot Work', 'Electrical Work', 'Working at Height', 'Excavation', 'Cold Work', 'Lifting'],
  auditTypes: ['Audit 5R', 'Safety Patrol', 'Safety Inspection', 'GMP Audit', 'Internal Audit', 'Housekeeping', 'Behaviour Based Safety', 'Compliance Audit'],
  incidentTypes: ['Unsafe Act', 'Unsafe Condition', 'Near Miss', 'First Aid Case', 'Medical Treatment Case', 'Lost Time Injury', 'Property Damage', 'Vehicle Accident', 'Environmental Incident', 'Safety Observation'],
  wasteB3: ['Baterai Bekas', 'Limbah Elektronik', 'Kemasan B3 Bekas', 'Kain Majun Bekas', 'Limbah Chemical', 'Stiker Galon', 'Oli Bekas', 'Filter Oli'],
  wasteNonB3: ['Botol', 'Kardus', 'PP', 'Tutup', 'Lid Cup', 'Cup', 'Karung Besar', 'Derigen', 'Lain-Lain (Galon Non Mountoya)', 'Besi Bekas', 'Ban Bekas (Kecil)', 'Ban Bekas (Besar)'],
};
